### ISSUE TITLE
Rewards off thread

### ISSUE THREAD

**Issue by TDaltonC** [DopamineLabs/DopamineKit-iOS#19]
I know that Basil Giflia renders rewards off the main thread. Is there a way to modify the SDK such that all rewards are, by default, rendered off of the main thread or would that create a bunch of unexpected problems?

**Comment by cuddergambino** [comment]
I have added a new optional QoS queue parameter for DopamineKit.reinforce() to version 4.1.4 #20 

This is so that now developers can manually configure which asynchronous thread the reinforcement function will run on, using a thread other than the main thread if they notice lag in the UI
